version: '3'

services: 
    postgresql:
        container_name: postgresql
        build:
            context: .
            dockerfile: ./docker/database.Dockerfile
        env_file: .env
        ports:
          - "5433:5432"