import os

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_REPOSITORY = os.getenv("GITHUB_REPOSITORY")
GITHUB_COMMITER_NAME = os.getenv("GITHUB_COMMITER_NAME")
GITHUB_COMMITER_EMAIL = os.getenv("GITHUB_COMMITER_EMAIL")
GITHUB_API_ENDPOINT = "https://api.github.com/"
WIKI_API_ENDPOINT = os.getenv("WIKI_API_ENDPOINT")
BOT_NAME = os.getenv("MEDIAWIKI_BOT_NAME")
BOT_PASSWORD = os.getenv("MEDIAWIKI_BOT_PASSWORD")
