"""empty message

Revision ID: acedfebf4925
Revises: 03c646ec9ba3
Create Date: 2020-06-02 16:15:57.567938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acedfebf4925'
down_revision = '03c646ec9ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organiser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task_manager', sa.Column('organiser_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task_manager', 'organiser', ['organiser_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_manager', type_='foreignkey')
    op.drop_column('task_manager', 'organiser_id')
    op.drop_table('organiser')
    # ### end Alembic commands ###
